# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Katas',
            new_name='Kata',
        ),
    ]
